ui/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    # ex: /dashboard/
    path("", views.index, name="index"),
    path("create-engagement/", views.create_engagement, name="create_engagement"),
    path("control-engagement/<int:id>", views.control_engagement, name="control_engagement"),
    path("confirm-engagement/<int:id>", views.confirm_engagement, name="confirm_engagement"),
]

ui/pubsub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

ui/myapp/models.py
from django.db import models

class Engagement(models.Model):
    name = models.CharField(max_length=200)
    created = models.CharField(max_length=20)
    controlled = models.CharField(max_length=20)
    confirmed = models.CharField(max_length=20)
    canceled = models.BooleanField(default=False)

ui/myapp/views.py
from django.shortcuts import render
from .messages.publish import publish_message, publish_control_state, publish_confirm_state
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Engagement
import mysql.connector 


# Create your views here.
def index(request):

    mydb = getDb()
    
    mycursor = mydb.cursor(dictionary=True)

    mycursor.execute("SELECT * FROM engagements WHERE created='v' AND controlled='f' AND confirmed='f'")

    created_engs = mycursor.fetchall()
    print(created_engs)

    mycursor.execute("SELECT * FROM engagements WHERE created='v' AND controlled='v' AND confirmed='f'")

    controlled_engs = mycursor.fetchall()

   
    return render(request, 'myapp/index.html',{
        'engs': created_engs,
        'controlled' : controlled_engs
    })

def create_engagement(request):
    name = request.POST.get('name', '')

    publish_message(name)
    print("Message sent")

    return HttpResponseRedirect(reverse("myapp:index"))

def control_engagement(request, id):
    eng_id = request.POST.get('eng_id', '')

    # print(eng_id)
    publish_control_state(eng_id)

    print("Engagement Controlled")

    return HttpResponseRedirect(reverse("myapp:index"))

def confirm_engagement(request, id):
    eng_id = request.POST.get('eng_id', '')

    publish_confirm_state(eng_id)

    print("Engagement Confirmed")

    return HttpResponseRedirect(reverse("myapp:index"))

def getDb():
    return mysql.connector.connect(
        host="mysql",
        user="root",
        password="root",    
        database="compta",
        port="3306"
    )
    

ui/myapp/templates/myapp/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Architecture</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">DGCCP</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Lien</a>
              </li>
            </ul>
            <span class="navbar-text">
              Architecture
            </span>
          </div>
        </div>
      </nav>
      <div class="container mt-5">
        
        <div class="row">
          <div class="col-md-8">
            <h3>Engagement</h3>
            <nav>
              <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Créer</button>
                <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">A Controller</button>
                <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">A Confirmer</button>
              </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">.
                <form method='post' action="{% url 'myapp:create_engagement' %}">
                  {% csrf_token %}
                  
                  <div class="mb-3">
                      <label for="exampleFormControlTextarea1" class="form-label">Intitulé</label>
                      <textarea class="form-control" id="exampleFormControlTextarea1" name="name" rows="3"></textarea>
                  </div>
                  
                  </br>
                  <button type="submit" class="btn btn-primary">Créé</button>
              </form>
              </div>

              <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                {% if engs %}
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Intitulé</th>
                      <th scope="col">Etat</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>

                    {% comment %} {{ engs | pprint }} {% endcomment %}
                    {% for e in engs %}
                      {% comment %} {%if s.sale[2:].split(':')[0] == "MA"%} {% endcomment %}
                      <tr>
                        <th scope="row"> {{ forloop.counter }}</th>
                        <td>{{e.name}}</td>
                        <td> Créé</td>
                        <td>
                          <form method='post' action="{% url 'myapp:control_engagement' e.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="eng_id" value="{{e.id}}">
                            <button type="submit" class="btn btn-primary">Controller</button>
                        </form>
                        </td>
                      </tr>
                      {% comment %} {%endif%} {% endcomment %}
                    {% endfor %}
                  </tbody>
                </table>
                {% else %}
                  <p>No  Engagements available.</p>
                {% endif %}
              </div>

              <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                {% if controlled %}
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Intitulé</th>
                      <th scope="col">Etat</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for e in controlled %}
                      {% comment %} {%if s.sale[2:].split(':')[0] == "MA"%} {% endcomment %}
                      <tr>
                        <th scope="row"> {{ forloop.counter }}</th>
                        <td>{{e.name}}</td>
                        <td> Créé</td>
                        <td>
                          <form method='post' action="{% url 'myapp:confirm_engagement' e.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="eng_id" value="{{e.id}}">
                            <button type="submit" class="btn btn-primary">Confirmer</button>
                        </form>
                        </td>
                      </tr>
                      {% comment %} {%endif%} {% endcomment %}
                    {% endfor %}
                  </tbody>
                </table>
                {% else %}
                  <p>No  Engagements available.</p>
                {% endif %}
              </div>
            </div>
          </div>
      </div>
      
      <br>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>